matrix:
  include: #allows to set up tests/deploys in different languages/environments.
    - stage: test # groups builds by type, add your tests here
    # Run Travis CI for R using https://eddelbuettel.github.io/r-travis/
      language: c
      sudo: required
      dist: trusty
      before_install:
        - curl -OLs https://eddelbuettel.github.io/r-travis/run.sh && chmod 0755 run.sh
        # optionally add our launchpad repo, but not needed here
        # - sudo add-apt-repository -y ppa:edd/misc
        - ./run.sh bootstrap
      install:
        - ./run.sh install_aptget r-cran-rmarkdown r-cran-knitr
      script:
        - ./run.sh run_tests
      after_failure:
        - ./run.sh dump_logs
      #after_success:
      #  - ./run.sh coverage   
      notifications:
        email:
          on_success: change
          on_failure: change
    - stage: deploy # this block builds and deploys the docs, it's in Python.
      language: python
      install:
        - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        - bash miniconda.sh -b -p $HOME/miniconda
        - export PATH="$HOME/miniconda/bin:$PATH"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        - conda info -a
        - conda create -q -n test-env python=$TRAVIS_PYTHON_VERSION
        - source activate test-env
        - pip install mkdocs==1 mkdocs-material==3.0.3
        - conda install r-knitr r-devtools
        - R -e 'remove.packages(c("curl","httr")); install.packages(c("curl", "httr")); Sys.setenv(CURL_CA_BUNDLE="/utils/microsoft-r-open-3.5.0/lib64/R/lib/microsoft-r-cacert.pem")'
        - R -e 'install.packages("Rd2md")'
        - R -e 'source("https://bioconductor.org/biocLite.R"); biocLite("BiocInstaller"); library(devtools); install_github("compbiocore/qckitfastq",build_vignettes=FALSE)'
      before_script:
        - source activate test-env
      script:
        - mkdir docs
        - Rscript make.R
        - mkdir docs/styles
        - mkdir docs/images
        - curl https://gist.githubusercontent.com/fernandogelin/08ecff3387dffc374c4abf06a577ab71/raw/083a383e51533feb20f3b03e6edcd9e86ddc59f9/dark_mode.css > docs/styles/dark_mode.css
        - curl https://gist.githubusercontent.com/fernandogelin/b02ee98f2f35ce4263093f7a1c66582b/raw/8c8b8a03203f2dbc9040ea2970fc888f14e08cb6/cbc-logo.svg > docs/images/cbc-logo.svg
        - mkdocs build --verbose --clean --strict
      deploy:
       provider: pages
       skip_cleanup: true
       github_token: $GITHUB_PAT
       local_dir: site
       on:
         branch: master
